### ISSUE TITLE
Remove dependency on k6's json and InfluxDB outputs

### ISSUE THREAD

**Issue by MStoykov** [k6io/xk6-output-kafka#1]
Both of the dependencies are so Kafka can format metrics in both of the formats. 

While it's probably not great to copy-paste this code the alternative is that any changes to those might break this extension which especially as time goes by will not be an easy thing to avoid.

Even now the InfluxDB output will need to be refactored and moved from the old "collector" interface to the "Output" one, which will break this extension :sob:. 

Additionally, for InfluxDB we should probably copy 1-2 configurations such as `tagsAsFields` and `precision`.

We also intend on updating the [influxdb library in k6 to support v2](https://github.com/k6io/k6/issues/1730) which may or may not mean we will drop v1, but also means that the API will likely change and that 

Given all of the above, I do think it's probably better to do this change now and drop any dependency on k6 that isn't the Output interface and its registration

**Comment by simskij** [comment]
Isn't it better to just let it break in those cases, to make sure someone contributing here handles the breaking change as well?

**Comment by MStoykov** [comment]
The problem @simskij is that I (or whoever works on the moving of the collector to output and then adding of infludbv2) am going to have to come back and fix this extension as well as we will be using it in k6 for at least 2-3 releases more so ... in reality this will save me doing a dance of fixes between the two repositories
